version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build
  test:
      docker:
        - image: circleci/node:8.9
      steps:
        - checkout
        - run: npm install
        - run: npm test
  sample_job:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hello world!"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - sample_job
      - test:
          requires:
            - sample_job
